import test from 'node:test';
import assert from 'node:assert/strict';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { mkdtemp, rm, readFile } from 'node:fs/promises';
import path from 'node:path';
test('MCP handshake, tool discovery, recording lifecycle, and error responses', async t => {
  const dir = await mkdtemp(path.resolve('.test-recordings-'));
  const client = new Client({name:'integration-test',version:'1.0.0'});
  const transport = new StdioClientTransport({command:process.execPath,args:['plugins/browser-replay/src/server.js'],env:{...process.env,BROWSER_REPLAY_OUTPUT:dir}});
  t.after(async () => {await client.close();await rm(dir,{recursive:true,force:true});});
  await client.connect(transport);
  const tools = await client.listTools();
  assert.equal(tools.tools.length,5);
  assert(tools.tools.some(tool => tool.name === 'record_enrich'));
  const started = await client.callTool({name:'record_start',arguments:{name:'mcp-test'}});
  assert.equal(JSON.parse(started.content[0].text).active,true);
  const stopped = await client.callTool({name:'record_stop',arguments:{}});
  assert((await readFile(JSON.parse(stopped.content[0].text).script,'utf8')).includes('chromium.launch'));
  const again = await client.callTool({name:'record_stop',arguments:{}});
  assert.equal(again.isError,true);
});
